version: "3"
services:
        redis:
          image: 'redis'

        nginx:
          restart: always
          build:
            dockerfile: Dockerfile.dev
            context: ./nginx
          ports:
            - '8080:80'

        app:
          build:
            dockerfile: Dockerfile2
            context: .
          ports:
            - "8000:8000"
          environment:
            - REDIS_HOST=redis
