version: "3"
services:
        redis:
                image: 'redis'
        appy:
                image: oleglola/app-serv
                ports:
                 - "8000:8000"
                volumes:
                  - ./appy:/usr/app/appy:Z
