apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    component: web
spec:
  containers:
    - name: app-serv
      image: oleglola/app-serv:2
      imagePullPolicy: Always
      ports:
        - containerPort: 8000
